### ISSUE TITLE
"Open" menu rendering glitches when closed in sub-menu

### ISSUE THREAD

**Issue by FichteFoll** [an-anime-team/an-anime-game-launcher-gtk#1]
When the main menu is closed while the "Open" sub-menu is open, weird things happen the next time the menu is opened.

https://user-images.githubusercontent.com/931051/186984015-0a453636-fd2b-4ea7-94d6-864bfe4904e4.mp4

**Comment by krypt0nn** [comment]
As I said in discord this likely related to libadwaita, so can't fix it. If you wonder the code is [here](https://github.com/an-anime-team/an-anime-game-launcher-gtk/blob/main/assets/ui/main.blp#L121)
