### ISSUE TITLE
Unable to close the about window while downloading

### ISSUE THREAD

**Issue by quazar-omega** [an-anime-team/an-anime-game-launcher-gtk#11]
[about-window-issue.webm](https://user-images.githubusercontent.com/56311398/192850172-410da49f-89c2-4c24-8d2d-12841aa64c40.webm)

While I was downloading, I put the pc in suspension and after waking it I opened the about window.

**Comment by krypt0nn** [comment]
Fixed in aa6f08f0fda6c51b20eccd1f35706bc3c1fe6391
