### ISSUE TITLE
Mention ebuild repo on release page

### ISSUE THREAD

**Issue by Schievel1** [an-anime-team/an-anime-game-launcher-gtk#13]
I added the anime game gtk version to our ebuild repository. (https://github.com/an-anime-team/aagl-ebuilds)
It would be great if you added a link to it on the release page.

**Comment by krypt0nn** [comment]
![image](https://user-images.githubusercontent.com/29639507/198688608-eb0e55da-a39e-418c-bcd2-5916850f4e55.png)

Not like it's my work but it surely should be named an-anime-game-launcher-gtk **-bin**, not just an-anime-game-launcher-gtk

Added link in repo

**Comment by Schievel1** [comment]
Users build this by themselves when emerging it, so why should it be called bin?

Packages with -bin suffix in gentoo are packages that are downloaded as a binary and then copied onto the system pretty much like packages work in other distros like Debian and Arch. 

If anything the other package, **an-anime-game-launcher-bin**, the typescript one, should maybe not have that suffix -bin because packages that aren't provided as source and only as binary, like discord for example, usually don't carry this suffix. 
But this is just some kind of an convention and not a rule you must follow.
