### ISSUE TITLE
Can't save edited config

### ISSUE THREAD

**Issue by frnmz** [an-anime-team/an-anime-game-launcher-gtk#16]
Hi, thanks for your hardwork!
So I accidentally pressed the button to download eng voicepack, eventhough I don't need it.
Now I have this "en-us" in the config file.
I just want to erase this line but it always failed as it says:
![image](https://user-images.githubusercontent.com/18339774/200176887-83aa00b6-c07c-4e4b-b8ae-9ef892b69b10.png)
I tried to manually edit the config from nano with sudo. But nano can't read anything in that file.
![image](https://user-images.githubusercontent.com/18339774/200176948-82336533-c0f8-45c1-8fc9-566fc59bf30e.png)
What should I do?
I downloaded the entire eng voicepack last night, and after logged in, I remove them from within the game menu.
Now AAG requesting to download the voicepack again to launch the game.

**Comment by Mar0xy** [comment]
You can select and unselect voice packs via the settings menu in the launchers. no need to edit configs.
