### ISSUE TITLE
Fedora packaging

### ISSUE THREAD

**Issue by ryleu** [an-anime-team/an-anime-game-launcher-gtk#18]
I'd love to have packaging for Fedora. Packaging for Fedora and packaging for Debian are very similar, so you should be able to knock out two birds with one stone.

**Comment by Mar0xy** [comment]
There is a plan to package the GTK launcher for openSUSE and Fedora you can find the repo here: https://build.opensuse.org/project/show/home:Maroxy:AAT-Apps

Currently only the neutralino version is available.

**Comment by Mar0xy** [comment]
It's now available simply select your fedora version by clicking on the download icon on https://build.opensuse.org/repositories/home:Maroxy:AAT-Apps and then add it in as a repo via your package manager or just download the rpm directly through the navigation of the repo.
