### ISSUE TITLE
无法打开 can not open

### ISSUE THREAD

**Issue by whtrys** [an-anime-team/an-anime-game-launcher-gtk#19]
logs
```
'/home/whtrys/下载/anime-game-launcher' 
/home/whtrys/下载/anime-game-launcher: symbol lookup error: /home/whtrys/下载/anime-game-launcher: undefined symbol: adw_entry_row_get_type, version LIBADWAITA_1_0
```

**Comment by whtrys** [comment]
> 

I didn't know which is the best anwer you want me to provide
![image](https://user-images.githubusercontent.com/69187424/206325908-fe2e787f-8e41-41ec-b7f0-97bad66faed9.png)
"已安装"means "installed" ,"自动"="auto"

**Comment by whtrys** [comment]
I have tried to install every package which is similar to the 'LibAdwaita' I had saw

**Comment by whtrys** [comment]
My English is poor.Maybe you know Chinese, so this is what i want to say "我不知道具体是那个包，所以我把所有可能是的包都装上了，但还是用不了"

**Comment by Mar0xy** [comment]
Sadly I don't know chinese but after seeing the versions I can tell the issue.

The issue is that the libadwaita packages are outdated since they are 1.1.0 but 1.2.0 is required.
Please try using flatpak instead which should fix this issue.
