### ISSUE TITLE
[Feature Request] Discord RPC support

### ISSUE THREAD

**Issue by Kagaminator** [an-anime-team/an-anime-game-launcher-gtk#20]
Neutralino launcher does have Discord RPC support, but GTK still doesn't have it, I think it would be a good addition.

**Comment by Mar0xy** [comment]
This will come eventually as this has always been planned to be added just hasn't been done yet due to more important matters.

**Comment by jiro-too** [comment]
Wait for #28 to get merged.

**Comment by Kagaminator** [comment]
> Wait for #28 to get merged.

Since its already merged I will close this, thank you.
