### ISSUE TITLE
fps unlocker conflicts with borderless window

### ISSUE THREAD

**Issue by nerd** [an-anime-team/an-anime-game-launcher-gtk#21]
the launcher hard writes the config for the FPS unlocker, which breaks borderless fullscreen. one fix is to tie `PopupWindow` in the FPS unlocker config to the borderless option in the regular config, i.e. when borderless is enabled, set `PopupWindow` to `true` in `fps_config.json`

**Comment by krypt0nn** [comment]
Added popup window setting to the fps unlocker section in 1.2.4
