### ISSUE TITLE
Unable to launch game

### ISSUE THREAD

**Issue by chinh4thepro** [an-anime-team/an-anime-game-launcher-gtk#25]
I keep getting ``Telemetry server is not disabled: log-upload-os.hoyoverse.com`` everytime I launch the game with the GTK3/Rust variant on Gentoo.

**Comment by chinh4thepro** [comment]
I am not using a proxy or anything like that.

**Comment by onlymash** [comment]
same
![image](https://user-images.githubusercontent.com/5838634/212521289-69b481c6-76b1-4b13-8095-1f3755f87653.png)

**Comment by chinh4thepro** [comment]
I fixed it by adding it in ``/etc/hosts``, and forgot to close this
