### ISSUE TITLE
Patch 3.4 not available？

### ISSUE THREAD

**Issue by CunqiShao** [an-anime-team/an-anime-game-launcher-gtk#26]
New version 3.4 has been published，the launcher patch version is outdated.

**Comment by c02y** [comment]
You can see the patch version in the settings is v3.4

But, I tried several times, it gets stuck on the `Applying changes... 100%`, restart and do it again, it won't get into the next step.

![image](https://user-images.githubusercontent.com/2135996/213162840-13cd22a1-8857-483d-86c6-3d6e7d4cb762.png)


The latest.log file contains tens of lines like:
```
[thread: 5535][Launcher/State/ApplyChanges] Patching GenshinImpact_Data/StreamingAssets/Audio/GeneratedSoundBanks/Windows/English(US)/1015.pck: failure
```

**Comment by Mar0xy** [comment]
The launcher automatically detects the current patch version available and allows you to download it either as a testing patch (which you get warned about) or as a stable/tested patch. If it isn't showing the new patch then it's likely that your launcher is pulling from the mirror which lags behind by 2-3 days
