### ISSUE TITLE
How to prevent download another voice pack when login for the first time?

### ISSUE THREAD

**Issue by c02y** [an-anime-team/an-anime-game-launcher-gtk#29]
For instance, I set the voice package to Chinese in the launcher settings, the Chinese voice pack is downloaded in the process of downloading the game data.

After I launch the game and login, it automatically download the English voice pack.

How can I prevent this extra downloading and use the already downloaded voice pack which is chosen in the launcher settings? I'm not sure if this is possible, if it is, how can I do that?

FYI:
- The language the game is using when I open the game is English.
- My system locale command's output is all `en_US.UTF-8`
- My OS (Archlinux) interface language: English
- Launcher interface: English

**Comment by c02y** [comment]
I'm confused, so in order to stop downloading the extra English voice pack and using the specific voice pack in the setting, I need download all the other voice packs?

**Comment by Mar0xy** [comment]
> How can I prevent this extra downloading and use the already downloaded voice pack which is chosen in the launcher settings? 

This is not possible as the game always expects the english voice pack on first run until you change it in the game settings.

**Comment by c02y** [comment]
> > How can I prevent this extra downloading and use the already downloaded voice pack which is chosen in the launcher settings?
> 
> This is not possible as the game always expects the english voice pack on first run until you change it in the game settings.

got it thanks
