### ISSUE TITLE
panic when clicking on settings at first launch

### ISSUE THREAD

**Issue by Schievel1** [an-anime-team/an-anime-game-launcher-gtk#3]
When I click on the cog after first launching the launcher, it crashes and get this log:

```
❯ RUST_BACKTRACE=full anime-game-launcher
[main] [set_state] state: WineNotInstalled
[main] [update] action: OpenPreferencesPage
[general page] [update] action: UpdateWineComboRow
[general page] [update] action: UpdateDxvkComboRow
thread 'main' panicked at 'Failed to list downloaded DXVK versions: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/ui/preferences/general.rs:455:26
stack backtrace:
   0:     0x55792aec8067 - <unknown>
   1:     0x55792adb958c - <unknown>
   2:     0x55792ae9dc44 - <unknown>
   3:     0x55792aeca3d6 - <unknown>
   4:     0x55792aecb466 - <unknown>
   5:     0x55792aecaf02 - <unknown>
   6:     0x55792aecae76 - <unknown>
   7:     0x55792aecae32 - <unknown>
   8:     0x55792ac6bb02 - <unknown>
   9:     0x55792ac6bd82 - <unknown>
  10:     0x55792ad0e447 - <unknown>
  11:     0x55792ad0693f - <unknown>
  12:     0x7f57308eef36 - g_main_context_dispatch
  13:     0x7f57308ef418 - <unknown>
  14:     0x7f57308ef4cf - g_main_context_iteration
  15:     0x7f5730b100ad - g_application_run
  16:     0x55792ac87e9a - <unknown>
  17:     0x55792ad79163 - <unknown>
  18:     0x55792ac8b142 - <unknown>
  19:     0x7f57305d234a - <unknown>
  20:     0x7f57305d23fc - __libc_start_main
  21:     0x55792ac75281 - <unknown>
  22:                0x0 - <unknown>
```

distro is gentoo, I installed launcher via the ebuild i have written. The launcher is in /usr/bin/ if that matters.

**Comment by krypt0nn** [comment]
Can't be a thing since DXVK downloads during initial setup. This error likely happens [here](https://github.com/an-anime-team/an-anime-game-launcher-gtk/blob/main/src/lib/dxvk.rs#L31):

```rs
std::fs::read_dir(folder.to_string())?
```

where folder is:

```rs
dxvk::List::list_downloaded(config.game.dxvk.builds)
```

so you likely don't have this folder on your disk for some reason. If you changed it after initial downloading - launcher doesn't try to create it

**Comment by Schievel1** [comment]
Yes, resolved it by creating the folder `~/.local/share/anime-game-launcher/dxvks. 

I have not touched that folder anytime. The launcher did not try to download dxvk. 
Maybe that has something to do with the way I installed the launcher. (as a direct package and not a flatpak)
Anyway, I will put that in the readme for the ebuilds for now. 

Maybe you should not panic if you get that Err from read_dir.

**Comment by Schievel1** [comment]
> Can't be a thing since DXVK downloads during initial setup. This error likely happens [here](https://github.com/an-anime-team/an-anime-game-launcher-gtk/blob/main/src/lib/dxvk.rs#L31):
> 
> ```rust
> std::fs::read_dir(folder.to_string())?
> ```

It is rather [here](https://github.com/an-anime-team/an-anime-game-launcher-gtk/blob/f4684dcf3278beaf601071581ab087c78374b946/src/ui/preferences/general.rs#L454)
```rust
 let list = dxvk::List::list_downloaded(config.game.dxvk.builds)
                        .expect("Failed to list downloaded DXVK versions");
 ```
expect() is nothing else than unwrap() with a message, which in turn is nothing else than panic!() if the Option is None.  

Instead of of expect you could match the option against some and none and leave the list empty if it is none. 

I will open that issue again, because I think this is still one. A program should not just crash if it can not find what is expected. I will make you a PR, because I wanted to do some things in Rust anyway.

**Comment by Schievel1** [comment]
> Can't be a thing since DXVK downloads during initial setup. 

Oh yeah about that: #6
