### ISSUE TITLE
Launcher asks to install wine even though System wine is installed

### ISSUE THREAD

**Issue by Schievel1** [an-anime-team/an-anime-game-launcher-gtk#5]
When I first started up the launcher, the blue button was set to download and install wine. 

Only when I did that it changed to download game later on. 

This is misleading, because I thought letting wine be downloaded by the launcher is the only option. Only later I found out I can set system-wine in the config.

System is gentoo, launcher installed as a native program via the ebuild.

**Comment by krypt0nn** [comment]
Fixed what should be fixed in c1af50b8c18ae064833c8c46563ba94c899aeffe
