### ISSUE TITLE
Launcher does not give the option to use system wine during setup

### ISSUE THREAD

**Issue by Schievel1** [an-anime-team/an-anime-game-launcher-gtk#8]
So that confusion #5 came from the fact that I never saw the first_run setup window. 
Now I do, and I do not know what you commited in #5 but what I initially meant was, that the launcher never gives the option to choose system wine. It just gives me a list of Wine versions to choose from.
I don't know if one of those is the systems wine or if all of them are to be downloaded by the launcher.  
![Screenshot from 2022-08-28 23-15-39](https://user-images.githubusercontent.com/85408625/187094925-4ce75377-7009-46c1-b6c5-f4a6545409c1.png)

(I can not make a screenshot when the menu is open, because that freezes any other program until I close the menu again. Including the one that makes screenshots)
I built the latest commit [c1af50b](https://github.com/an-anime-team/an-anime-game-launcher-gtk/commit/c1af50b8c18ae064833c8c46563ba94c899aeffe) but problem is also there in 1.0.3.

I think at this point I don't need to tell you I am running this in gentoo and as a native program built via ebuild.

**Comment by krypt0nn** [comment]
Added in d8a48caf9765cd39edb40097675f6fd11f442217. Will become available in future update (1.1.0?). Closed
