### ISSUE TITLE
[Flatpak] use portals for filepicker dialogs(that respect the current desktop) and getting directories

### ISSUE THREAD

**Issue by SViN24** [an-anime-team/an-anime-game-launcher-gtk#9]
Using [this](https://github.com/flatpak/xdg-desktop-portal), the application gains the the file picker dialog that works best for the respective desktop environment.
It also allows the user to easily give the application access to a location outside of the sandbox without compromising the sandbox or having to deal with Flatseal.
This is mostly useful in the launcher setup where a file prompt appears if you decide to for example change the install location of the game.

**Comment by orowith2os** [comment]
It's possible to use portals easily by way of Rusty File Dialogs, so it's most likely not going to be too much effort to go through with

**Comment by krypt0nn** [comment]
Added in 8efd07c7fd45ba4d3cf3ca0d558e847d0889ef0e. Closed
